### ISSUE TITLE
Shrinking the header

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/kptheme#2]
Currently the header takes up a lot of space unnecessarily. We have already shrunk the header on the homepage.

TASK: The header on all pages other then the front-page should be reduced in height substantially. It should be smaller even then the front-page not larger.

**Comment by laceysanderson** [comment]
I was under the impression that this had been done; however, the changes are not in this repository...

**Comment by reynoldtan** [comment]
I have attached an image showing versions of the css file. It appears the css in portal does not include the rule to shrink header. Both my dev and repository versions appear to be the same. To fix the issue, I would recommend to add the missing css rules for #header and #header img into the kpstyle.css of portal. Please do not push/pull this file overriding the portal version of kpstyle as I have css rules in the repo for updates pending review.

![versions](https://cloud.githubusercontent.com/assets/15472253/26466952/ddc1f85e-414d-11e7-9eaf-94a6649e37a0.jpg)

**Comment by laceysanderson** [comment]
Fixed
