### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/kptheme#4]
In each crop, the overview page contains image that is right aligned and creates unecessary negative space

![Screen Shot 2022-02-24 at 2 08 13 PM](https://user-images.githubusercontent.com/15472253/155599643-c4ae67e9-da69-4ad5-b856-f541a565adf3.png)

**Comment by ruobinLiu** [comment]
I've reviewed layout for every link under both crop and genome assemblies. Everything works as expected, except for dry bean. 
![Screen Shot 2022-03-07 at 1 49 51 PM](https://user-images.githubusercontent.com/45402954/157107311-a15b138e-6300-40b0-8d6a-b43ae698c794.png)

**Comment by ruobinLiu** [comment]
Everything looks fine now 👍
